go.mod
go.sum
infrastructure/cmd/parser.go
infrastructure/cmd/parser_test.go

The standard `ParseDuration` in `time` package does not understand `d` as a valid unit because it can cause an indeterministic behaviour where two days contain summer time switches. For the case a PPPoE client session exceeds 24 hours, it failed to parse the time as shown below:
```
Cannot parse "01d10h57m" to a duration (key: "[1]"): time: unknown unit "d" in duration "01d10h57m"
```
This PR fixes this by xhit/go-str2duration which understands `d` as 24 hours.

Fix time column in PPPoE client sessions

---

Cargo.lock
Cargo.toml
README.md
src/application/metrics/bgp.rs
src/application/metrics/ddns.rs
src/application/metrics/load_balance.rs
src/application/metrics/mod.rs
src/application/metrics/pppoe.rs
src/application/metrics/version.rs
src/di/container.rs
src/domain/interface.rs
src/domain/mod.rs
src/infrastructure/cmd/parser/interface.rs
src/infrastructure/cmd/parser/mod.rs
src/infrastructure/cmd/runner/interface.rs
src/infrastructure/cmd/runner/mod.rs
src/infrastructure/config/env.rs
src/service/interface.rs
src/service/mod.rs

Closes #63 
Add a new label called `local_ip_address` that is collected from `ip` command to all the PPPoE client session metrics.

Add local_ip_address label on pppoe_client_session_*

---

src/application/server.rs

Replaces `axum::AddExtensionLayer` as it has been deprecated since #79.

Use axum::extract::Extension for DI

---

src/application/metrics/ddns.rs
src/domain/ddns.rs
src/infrastructure/cmd/parser/ddns.rs
src/infrastructure/cmd/runner/ddns.rs

When ddclient does not update its status, edgerouter-exporter cannot expose metrics due to parse failure.
```
interface    : eth0 
[ Status will be updated within 60 seconds ]
interface    : eth1 
[ Status will be updated within 60 seconds ]
```

Fix DDNS to be properly handled when misconfigured

---

Cargo.lock
Cargo.toml
README.md
src/application/metrics/ipsec.rs
src/application/metrics/mod.rs
src/di/container.rs
src/domain/ipsec.rs
src/domain/mod.rs
src/infrastructure/client/mod.rs
src/infrastructure/client/runner/ipsec.rs
src/infrastructure/client/runner/mod.rs
src/infrastructure/config/env.rs
src/infrastructure/mod.rs
src/service/ipsec.rs
src/service/mod.rs

Metrics and labels are designed to be compliant with [dennisstritzke/ipsec_exporter](https://github.com/dennisstritzke/ipsec_exporter) but edgerouter-exporter uses the VICI protocol to communicate with the charon daemon.

Add support for IPsec metrics

---

src/domain/ipsec.rs

Follows up for #95 
```
[2022-04-12T22:25:24Z ERROR] failed to collect metrics: missing field `encr-alg`
```

Fix missing encr_alg field caused scrape to fail

---

src/application/metrics/mod.rs
src/application/server.rs
src/di/container.rs
src/infrastructure/client/runner/ipsec.rs
src/infrastructure/cmd/parser/bgp.rs
src/infrastructure/cmd/parser/ddns.rs
src/infrastructure/cmd/parser/interface.rs
src/infrastructure/cmd/parser/load_balance.rs
src/infrastructure/cmd/parser/mod.rs
src/infrastructure/cmd/parser/pppoe.rs
src/infrastructure/cmd/parser/version.rs
src/infrastructure/cmd/runner/mod.rs
src/infrastructure/config/env.rs
src/main.rs

Error messages are now pretty printed with its root cause:
```
[2022-04-14T17:16:04Z ERROR] failed to start application
Error: error reading environment variables
Caused by:
missing value for PORT
```
```
[2022-04-14T17:16:18Z ERROR] failed to start application
Error: error starting server
Caused by:
Permission denied (os error 13)
```
```
[2022-04-14T17:18:10Z ERROR] failed to start application
Error: error loading TLS certificates
Caused by:
private key not found
```
```
[2022-04-14T17:17:21Z ERROR] failed to collect metrics
Error: error executing /opt/vyatta/sbin/ubnt_vtysh with ["-c", "show ip bgp summary"]
Caused by:
No such file or directory (os error 2)
```

Improve error messages

---

src/domain/ipsec.rs

```
[2022-04-17T05:01:24Z ERROR] failed to collect metrics
Error: error retrieving IPsec SAs
Caused by:
0: missing field `prf-alg`
1: missing field `prf-alg`
```

Fix missing prf_alg field caused scrape to fail

---

Cargo.lock
Cargo.toml
src/infrastructure/cmd/runner/mod.rs

This PR strengthens and enriches error reporting by:
* validating status code from processes
* including stdout/stderr from output when the command fails
```
[2022-08-25T16:03:42Z ERROR] failed to collect metrics
Error: error executing /bin/ip with ["--invalid-option", "addr", "show"]
Stdout:
Stderr:
Option "-invalid-option" is unknown, try "ip -help".
Caused by:
Process exited with 255
```

Validate status code from processes

---

src/infrastructure/client/runner/ipsec.rs
src/infrastructure/config/env.rs

Refactors `crate::infrastructure::config::env::ViciPath` using `dervie_more::AsRef`.

Derive ViciPath with derive_more::AsRef

---

Cargo.lock
Cargo.toml
README.md
src/di/container.rs
src/infrastructure/config/env.rs

This PR allows configuration through command-line options as well as additional features like `--help` and `--version`. Currently, `--log-level` is not implemented as configuration is done after logger is initialized.
```
admin@ubnt:~$ ./edgerouter-exporter --help
Usage: edgerouter-exporter [OPTIONS] --port <PORT>
Options:
--port <PORT>
Port number [env: PORT=]
--tls-cert <TLS_CERT>
Path to TLS certificate (if not specified, exporter is served over HTTP) [env: TLS_CERT=]
--tls-key <TLS_KEY>
Path to TLS private key (if not specified, exporter is served over HTTP) [env: TLS_KEY=]
--vici-path <VICI_PATH>
Path to Unix socket for VICI [env: VICI_PATH=] [default: /run/charon.vici]
--ip-command <IP_COMMAND>
Path to ip command [env: IP_COMMAND=] [default: /bin/ip]
--op-command <OP_COMMAND>
Path …
```

Switch to clap

---

src/application/metrics/mod.rs
src/application/server.rs
src/infrastructure/client/runner/ipsec.rs
src/infrastructure/cmd/parser/bgp.rs
src/infrastructure/cmd/parser/ddns.rs
src/infrastructure/cmd/parser/interface.rs
src/infrastructure/cmd/parser/load_balance.rs
src/infrastructure/cmd/parser/pppoe.rs
src/infrastructure/cmd/parser/version.rs
src/infrastructure/cmd/runner/bgp.rs
src/infrastructure/cmd/runner/ddns.rs
src/infrastructure/cmd/runner/load_balance.rs
src/infrastructure/cmd/runner/mod.rs
src/infrastructure/cmd/runner/pppoe.rs
src/infrastructure/cmd/runner/version.rs

The `Controller` instance has not been wrapped with `std::sync::Arc<T>` since #200 which wasn't intended. The change in #200 has caused `Clone::clone()` to be called which are unnecessary.

Wrap State with Arc<T>

---

Cross.toml

The latest tag is currently based on Ubuntu Xenial which comes with glibc 2.23 so it is still compatible with EdgeOS 2.0.9 that is shipped with glibc 2.24-11+deb9u4.
* Ubuntu Xenial Xerus: https://launchpad.net/ubuntu/xenial/+source/glibc
* glibc 2.23-0ubuntu11.3
* Debian "stretch": https://launchpad.net/debian/stretch/+source/glibc
* glibc 2.24-11+deb9u4

Use latest version for ghcr.io/cross-rs/mips{,el}-unknown-linux-gnu

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Migrates to dtolnay/rust-toolchain as actions-rs/toolchain seems to be no longer maintained.

Migrate CI/CD to dtolnay/rust-toolchain

---

src/infrastructure/cmd/parser/bgp.rs
src/infrastructure/cmd/runner/bgp.rs

The output from `show ip bgp summary` and `show bgp ipv6 summary` are unable to be parsed when any of neighbors are longer than 24 characters as `Neighbor` and `V` are adjacent to each other in this case:
```
[2023-07-26T09:51:29Z ERROR] failed to collect metrics
Error: failed to parse BGP status
Caused by:
error Tag at: Neighbor                 V   AS   MsgRcv    MsgSen TblVer   InQ   OutQ    Up/Down   State/PfxRcd
192.0.2.2                4 64497 1000       5000     128      1      5  01:11:11               9
192.0.2.3                4 64497 2000       6000     128      2      6  1d02h03m              10
192.0.2.4                4 64497    0          0       0      0      0     never     Connect
2001:db8::2              4 64497 3000       7000     128      3      7  03:33:33 …
```

Add a workaround for ill-formed bgp summary output

---

src/infrastructure/cmd/parser.rs
src/infrastructure/cmd/parser/bgp.rs
src/infrastructure/cmd/parser/ddns.rs
src/infrastructure/cmd/parser/interface.rs
src/infrastructure/cmd/parser/load_balance.rs
src/infrastructure/cmd/parser/pppoe.rs
src/infrastructure/cmd/parser/version.rs
src/infrastructure/cmd/runner/bgp.rs
src/infrastructure/cmd/runner/ddns.rs
src/infrastructure/cmd/runner/load_balance.rs
src/infrastructure/cmd/runner/pppoe.rs
src/infrastructure/cmd/runner/version.rs

As `Parser` only accepts `&str` as its input, its lifetime does not necessarily have to be generic. This PR changes the arguments that `Parser::parse()` accepts and introduces a new generic associated type whose lifetime parameter is `'static` most of the time.

Reduce explicit lifetime parameters of `Parser`

---

.github/workflows/cd.yml
.github/workflows/ci.yml

This PR (hopefully) temporarily sticks to Rust 1.71 since MIPS GNU targets no longer receive Tier 2 support.

Use rust-toolchain@1.71 since MIPS GNU targets are moved to tier 3

---

.github/workflows/cd.yml
.github/workflows/ci.yml
Cross.toml
README.md
rust-toolchain.toml

Use build-std as MIPS GNU targets are now tier 3

---

src/application/server.rs

Not exactly sure about why it fails but `GET /metrics` has failed due to `COMPRESSION_ERROR` on client side since nightly-2023-08-09 when it uses HTTP/2.

Disable HTTP/2 due to COMPRESSION_ERROR on client side

---

Cargo.lock
Cargo.toml
src/application/server.rs

HTTP/2 support, which has been dropped since #377 for some reason, now becomes available.

Re-enable HTTP/2 server

---

Cargo.lock
Cargo.toml
src/application/server.rs

Update to include fix for:
Crate:     tls-listener
Version:   0.8.0
Title:     Slow loris vulnerability with default configuration
Date:      2024-03-15
ID:        RUSTSEC-2024-0341
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0341
Severity:  7.5 (high)

Update tls-listener for security patches
